#pragma once

#include <string>
#include <unordered_map>

namespace Encryption {
enum Method { OneTimePad };
extern std::unordered_map<std::string, Method> methods;

const std::string pad_key =
    "RKSTXLLRXRFUXLGBLNLQKKELFJRUDCCWZHYPADMARYBSUUGLLKFSVEZWMQMYUNMXRGEGYCPZQB"
    "ZKRVEYSJEKQAEZWDKZDYRMXWHQDVPBMDTDYKRVENBPPTHLDKHVWWYTRYFQTTFEKAVTNVXYQTXG"
    "GHVFPSVNDUEYWDYKMXWFDMEHYHVJWRPFZRMUSDYLDEVLHBSHQWMURFSNXENTMSHVGSCHUZMBEX"
    "PNDPDWFJANCCNPXLNELGAWFZFDAGZVTCLLWXFRJBNGFLASWKMNXMWTNTWEPTLCBZZLTZKHMKZR"
    "UPAPJUPSNFSUHDMZCCPWBEVRLXSCWNPKUWDHXJEARJCDUJSTHAUUVLJTYXSWVTCRAWLKGBJTJT"
    "XNTDASHBPKHSRZDPFGEUJAEXFJCQUXUYZHDYHYEMSWNLUKFCUWNKDSBMDPUMMUHXVPKDKXFVAM"
    "URTJDSFKLAHNQRHBNWEKBQSYMYBXXJLYASVSCDKWTKHFJPDXQJCFSHQSNNFCWQERWXKWKLAKPY"
    "YTJKJJTGQRWDPKJKRZDNKCLZFFTBKYHBPAQNBDMKQFWRKAFPVHMPTZFQTHAZLVFMCMUZXZBYZP"
    "RXKSSQUHKTCAPDFKWZAVJUPPNQFXTXSZJAQVWVPHPKPCAYMMCKTHMPFMVMRCFHXDHPZVLDVGCV"
    "RSGJFYTVVZEYHWRXNRVFPUYUFPDBXAQYKBHUEXPKNPDPMGKSLHLDMCBVYFMADKASGAUBPVHVHC"
    "EWEUNTGHYHKZGMXXBUCPUPJEMUZNAMVFAPKXDLSYWGBKLKALPJDRXCSZGNJEHHRFMLGWQYCNSE"
    "WERBFAQSBWFNWGDLQFFQNCZQNHGEPGGMJWLUQHMXTCPWJTRMBMZCKPAJSDLRCQPMAHWXFXKJPQ"
    "KETBEHXTRQSPJHDKBLCBWWCTHGAXTTPQULXBRYDRZCQCRNDERQDEPQUDCEDZZCWWPPAWFKCNLF"
    "UDWBYXTBPLLFLVZPKSMRDKRTNBNPVNMYEKLKYGFYHMHCWHBJMZWCKQMJHVBCMJTGNEDMBEKMGT"
    "LJSRHTEJHDRRHSJAPYJCUFHAWFEMRURHMQWUEPYJPKKDNJABHWYMWJYBVGYDLTKTKKPZEDCNXB"
    "TFXTUNFXPUYNYNBWRSNXMVGBWEPPPHDFFTSYGCPMMPLQZFBUWGZAHMNZTVNRCEPWPTGBMMPSGB"
    "DRHPLSQYNDBUXFMZQMGQUUXCNJAQBKZCAUPBKMABUBWVXYBDAMYNLRDHWVLEUMQLTAYQUQFCYS"
    "ECADKCGPWRRSWPMGMTYFQZZUEMELGAUKUREKTFSXKWUCTREBFTCLZYKKNJKGBPPRFYLLTBYKEE"
    "MCCKMCWBVAQYPUCBWLDVWCWTPPCFHEVRXGUZVSTZKZJBQUJEVXKXRNLSTWWKLNQQPUCULWFQUX"
    "PYQWDRMAHQBZAMXRMQHWZBKQKBEZRQKKQHDQVTNCCHDSPRYSAPDZAQLCWJYXAQVUBUQMFCKMUF"
    "KNTWRMTMWEFXPQEZMVCGPFECVJSZBBDHJFBZUTBQABVVRYQTDVEQCYMYCVYCPMMPUPMQAGJGVA"
    "GMRSTGMGGGCRVKWWMVGBFRAMVDENKQQTMWLTMWRKDVSDKTMKUEYHJRBYNSTZZZQEATMLFQEHAW"
    "PABCHHJUEGMLRRMTNMVQUNPEASXLWBMFZKSGNEQDWLVUXXCBFCVNBYWPGMSDMKQHEQRBGLUXCV"
    "DWUFLGUEGDASLXLTLHSJDSPKMVZBTUBBLWHWCEFRVHLGTVUKFUZEXDVDANCCFKTXTRAPRMCSUB"
    "RETMAXNVMGPDKSSXPSTUMFZWCWHNZJCBVPSGZVUEXLRHSDJHSGDNXLMEETCSCJZRJNQABZENGR"
    "BQXCPYWGKNJREZWECMNPNTBEUZGYZMUUQCCFGQPRGMEFDKDRFAHZEYNWYVKWSBNCEDCCWYMLNL"
    "FXPGZYJMSRKRQDZDRMLBDPZLRFCCQAEZRNVQXXNXWVWPUPUSKSDTKSADDXVXQBEQEFTJHWWCKK"
    "CMHENXLCDVKQBRBNJZYMQSLPSSLWHSAYDDGBAPSMHHSJPUCMQMDSYQGZGVQHZVDUBERBMPMEGU"
    "ZKCEQSDAFPDNCCXMVYEXLJUXXTUFDGUGHMZTBWRNDJEECDTBNBGWXFAKSCTQNELPUKJUWKAPUT"
    "JQHXQKDDYEZTMNDFYPPKEYWUPRNRBJEEYHPUMFSMVSGTLQURELJRKEQQQBTYWEBRDAZGDGVNWP"
    "ZFMBLTSTNAEWBDTXVXBCZYPXXFNXFRPGWMWXFDLHJEMHJQSYCCPFSUEZTZZZEYLMSLMMZMQDHN"
    "FYULLTHZWFNTNJFUWHTYJSSSBZGUJKXQFAQYCAAKWHUFXAVBJDQPFNQDHQPFQUTBUQNRJDYCVX"
    "YZRYRXLJSKCFVZNDBCNXVMRGRWVAYGMMQBGNUBKXQNRAYVXWQWRHVPVEGBZZXHWDSGHKUKREPT"
    "UGUCAJBBMCHMBKFLSDXEDTGWWRLFNZTSVTUATPXQNVHRTVMYEZGKCGKDEGMXJQQZBWGMKBEXUB"
    "DPCRNWQGMEWWBPMKJPGQCEXKAYEHNNLDJYNKJAVZDZSANGJUGGQFSMYDPXRDHVJMXZGVDRANSJ"
    "LRMTXJPRJCJUWWRPANQPHSCABAKMJTDZTAHWALYYUXWQNXJDMYQXBUEEXNYFUPRVLPGSURCAQP"
    "RZBPVUESENDCFZDKMMZYRQAYWWBCDVWTXKKFZHBFBMFSJSTSYHCLUMVEZCMHUYGXAHXCDDHYSG"
    "ZHXAKJTFSGQFHDAXNHURNTRHEULBYUVPSGQGXBFCSHRFFGGHFNJTEXUPHKRQDHDFGSQMGZCRQT"
    "YGDKHPRFSTAQKEDEBJFMCYDKYCKHDECMFMANTARQWJDAQQSZHWEHQAJYZKCHYQCQGBWAXWRVXC"
    "YVKGEEZADVKYQDMNHFBNSQUQEEFFBABGWQRRUMDQKEMPZMKJWTQNQUXNCUVTLAYJSPFBYHTVUB"
    "HZMBFYESGVQECEWCFGYTZTZJGXGUJVRBNBHRAWJZJGWUFNKLXMZKEYPXEXBBNJFHFJWCTZKZDC"
    "SSYBRNPXUPXDEKARCRTQLVYCRPQQBJSLZDUZBCWVXKHYJMFSMYPUMRYDJHWZHXBHLYSBNADLQT"
    "RQGQWSWGKVRJBQGTZYGZKPBVUVRSJCHNXAPNRQVQXKTMSPQKSZRVMCJTWBHGRQFAVEBSCXTXLW"
    "UQKGENRPBEYCPCEAJXZVMNQAFUZDNQLXRLUKFELUATNKDGJACQLYDSQDBWFHXWHRDRXCDHDBVM"
    "TVJYUKGEUJWNYDBZEBTLFGQXQXLCAPFJUCBSPSDSFXABANLWMYZZDMXLNQNMZRLEGMEELEWLDT"
    "KYKXVSBXVBZPUJZLKJAQFTBDTKSLMNYLDMVFLLRWQCGVKVXKANVLMUWKJTUKREENQFXAQVNLYQ"
    "FXYSMDAABKCFDDZCCLZEDCTFMCVLLUJXLNUSWCDAYTRBLGBGKLYUKRDMQLEENGZSMUBQSQWXBF"
    "VGQZMHAHURUMBHSWCWTLVFXZPXXPQRXFMKPLBPNWJUXKNDCDDBCDRRHWLMYHYJRWCNPLRHLDKR"
    "NUQPRRWMGVDZGBVMCXREMTQTUUZBVSYMXBXVWAHLLQNLVQYPCNLPQKPZKQRYCZDBUXLTPMFWTJ"
    "NGTWWHNEKTDXQLGBVPVDVJMSLYLKLTNHYKGACEUKPLJBEWARREZDYSGQALRXZNVEHYGKLHEMME"
    "GKRCNMJQFWUEAMKKPZDWMXRANJCGQTSXVVDKCMVBSHABAFMFJSZJKZYXNNPPTJYLZYPEBHVCQE"
    "VNRBAJMRBMKVLSPSHQBELNJKQSNKEDRWAMEMQCRGUVJAYUCSQBNZNLFMFHPCYXFFHPKMVAHWPE"
    "FZYVMFWXDNJGKLFDPRVJNCATCBAQKWTYARJWYQCNYEYYRLSRRLZGDYBQNBDSYJLJNNKKPZPNUN"
    "PHNEGAJUESYZSZJFLEFZKTJSQBEYGFRXWAFLHCJTKXVGCTFSUVVPYFJHPUAPAMAZKYMPUSDVCR"
    "HWTKPMLSVHFPYFFPQPBSGXVSBAVERGGVDQCHHYBWRJTQCAPBXTGLTEKJDMRNRBHUDEWMGDAMNE"
    "JJUXGJHEEJJYQEAHBNHEHLEDLB";

std::string one_time_pad(std::string msg, int enc_dec);

std::string encrypt(std::string msg, Method method);
std::string decrypt(std::string msg, Method method);
} // namespace Encryption
