#pragma once

#include <string>
#include <unordered_map>

namespace Encryption {
enum Method { OneTimePad };
extern std::unordered_map<std::string, Method> methods;

const std::string pad_key =
    "HDfe0`>k}U;\\H5y$dA@Oa\\qjy,_63@-'HdO^NDeb[PvzAFE]NVsDJUgztX58,fjZukfVG*Y "
    "`$nUcG?C=a8j+,nDdO()>8iGu=`w_G\u007Fc\u007FM!\u007Fi%^/"
    "3K7xxegcRGxN2_y5rLkQklA.CNL#Y "
    "<>{DpmX}P}W9MdNchj<`^11s$SI-~Ol8chD6z32leul:DR~*~DK7}z7W/"
    "!!%LX7Ys\\`yj?N%>\"+^/PlY8XR*%[+kqllvP.K\u007F6B/"
    "crfb}[Nj%aC~J9Xi%75{r;@6y;4\u007FBLI(:x4^zM.q9&S!\"X|LLM%0?`av/"
    "Cx,Xv]$'<+I{Z=}^3NrwE_7rSvW5x23cR]_`7TYz9bFxS9{U<&0MY('i;??R5aCw7KNK\\k/"
    "p\\`~?_pRM*[XbW%G5q_IU(z%$A&y]m8CD?#Q<I#])1g3v%+e<_t3lqezBjN$xlvHu)(/"
    "QONIy1qnOHeMLy_-&9|_+8E\u007F~-qHh)qM:C/+7ut/MHlqF<d0TTY&/"
    "1fl*cwZ{TSjA&n(j&$_e4kQWtHdo1iyY}%7*r<Y<;#Bp!z8',rZ>:mK\"VeK'{SzWdpnJX) "
    "QCe/)(~^ND+3?.>%$9h?2xO1((N+4$%<Y(6= "
    "BV7]Ql'UUH\".|WP5lB04lz1k@4oexkn4Y_~Fziv3WFLQ'(OpE7{}t.1$06\u007Fe,yja:Pl["
    "M|9\"hyDO5XE'fc<.gZ}o'T-YO\\BRJ|AmQ@_+BTi#67Mmhl<-EP-o?CE.!t\\i*d@F|9o|<a$"
    "}iu}.|Bp]B8o~U33Rr:-g?i@JG`=~-Hg=:Jy+$x$3}lj0gL=TZ-Rkm-Z#$>x?hz@8#+ZIC/"
    "\"tPJX-Pq'eOJG*,pjmJ@+Th){l6'H}:Nc/\u007FQ2 "
    "(K|gVMnn?\\\u007F!YeMf\"MwdUj,lfUG6DN?4'e}Ok<wIK!$y0WHOrZf6g4`k>XUd,bBi&$|"
    "qB<Z<=LByah@iz2053IZb5,Q[XCK:9Xa`RHIa=>!Y#P0c<kQVJ=WAszUPZA`s8kAmf$k\\E "
    "P'93HOBk$3-SVQ-@0F7-4g@v5q2!tn7+Uq?X+1H+`tE\\;kZE=HGTUCsnjK_XL_af,\"CskZ/"
    "\"L@cKhEEg_m5`OgunfR,UNo6R6.ZoL8W+<c0LMCI\"8K[HmD+hz0q4w{h.,"
    "A3QNydRLebpS\"7!EW(+eOC--5qt;RO)b2*Ubw[C'09tFojaM'*%`QvE<A7x+BItJZSX`"
    "ev48T1;w'X&Yg=c:]Yf]XnA>*A9*gWr8ra]*hVAmWb\u007F?JsnVPqttu07daC@6xPHk2~'"
    "SGqDuSM0'/:t_FP'qi<?ye'Vg!Ne#l/"
    "\u007F4}R-6sCr,F;6k{`Iy)Lu^VLw~p]XMW\\vHxN?ee "
    "!;ynmhr@6Bg`Ex,#X!twn-}J9wV+bq28\\;hq_KQH)]JQ%Em;.e7H!8|{9S\u007Fth)y+(c; "
    "wL[2Vo;sKaDX7[b+N\u007Fo!9<>\u007F`y;SZX,Gq\\E'luzoe!,D?*V8}AmZy')lz`9`"
    "myiA}&DCB\u007F#;(N*@c>NXExvP/"
    "$j#RGu%Rhh$2eNHk)cii1\u007F(##}h+!:[F8IJ$RYZ,UcOb)u7HM#>>()?(:J[lXS+NSh "
    "O3|v~R/"
    "u{ud+6ieHp-m>f)I!aDVr&^qIf@FNHC$.{NV|;g)\u007FCnbaIK$r3Fr1<'{-Cwx*IgHY?"
    "Vogsw]:~0cUYlpD+[\"+j!Nw =t[VK QtE "
    "?W0ky>5#\"sXJi2P^)s^pouM@e>!b1F@-@){+Pk3]n$_#[NECjy1P?I\\!r;j],]DScPp){{r%"
    ".JWJ'<7_\u007Fe*9(xLK\\-tuer\\Ul`gLVRaO)z@~R=,`E\"]\"@Q9yF8`!LIgU "
    "@h#_6v=%58%\\ms^SdCgj)GX QsOY#JX-6[Px522`9/$x7:\u007F,2p91o4:Z "
    "JU?tZm_Z|KCw<Up[^6!JC+5(fRseM#\u007F6;i3!Gvfn*($.g3,\u007F3(K%mGOX@J}{"
    "jFZQ2'0/2r;Ic?<TB)YwP:O}n@zU[iF%u=0(Bzjk[n<\u007Ft "
    "wA69Sx^)O;()[yV%.!N$aWu*D[$t70\u007FmfC^,s`eIW#1V=u&i$ X@b@$@'!o0IbY'-u "
    "7*5mHpGU)7*=\u007F]?>HO(-SUZ_gB09NJ9'3'vfn(6s&-I0Qy(V4i>j7rpjj.FT "
    "hVASsn3_n{wv[5vSt7AyB0?@p/ZY\"gUp`\\\"z/v<4q<\"_vY;4GiQNe4<_[]0A.T "
    "b?+t27|*4C~HB'Py+o*hre-I#q>RJD49D;BEoVe<VdHP?L@A]er\"[Z3%$dlSe5|CE[z)"
    "vIVgLN%l+U&$8o2u*Du(;wqU8Vtj>(8! "
    "$pR^D\"r2)h?\\\\#/"
    "qFf,Skr]g61IrxDVve6Tcu`N4D%aW20t\u007F>KJT(9RP=))+1z?acuaOENHEQu=_RBAO>tC:"
    "%V%:9WNF';Tj_]`gV^^t5btQ:0D_<;%5.h |!K~)<K3BwFe*6e7x!nCq "
    "VC-ttsxup+c%^$_ZU#p3_rfZR70\u007FsK4K{KgGyM:*#=?;XY6N@;e;Tg9Z;"
    "Upf\u007F1SK:<Fc alHEQyjAH,~,xvu5^c~r&>uD*kWupw9:+jzh+XSyWEVHtc>|=;H6 "
    "q-c^823Guzgk/"
    "vp{yRKsDjT+mKai6(CW*}fNaiRc6e]R+)XL,WGWjlmw(!JyzIh:,^Y!|SB^*M]S'Y(2wRb(>H|"
    "l_X#PCpcPiw>ujxC'>j{,}3 "
    "!#y8%V_:)EGC?8eV-H\u007FP0,Tebco&:G#i5Bi:`ucJV\u007F;_JJidbp2x:Hl?4i~)u;?,"
    "&qw'K^qmdeIGyH_pGo?sLi2FHn6KiR/x)R{`Bw<j/Hot\\stu.+OM\" "
    "p$\u007FJ&@5m|j0u$+k\u007F)BwvKq%UIvXOBIf/"
    "j{0[DHp9+ESs<PchN\"q%IE}#vVU=x1P;F,MRRYy=P7fH6NYbO)5Qc%Lxl[+xN]*M\\J/"
    "4%{;T,</"
    "FRa>:-NlrM_n@'p)-%Nj$d4oq#-eNjy<k,EFdza35$k}(w}=p+yPBs\"\u007FIIFO!#s`&"
    "epnfh<FyOedSL<kF':PG|N^*hgA@s#G9KC_/(>XlqGgM>,$f,r]`x$ZpCrh/"
    "+::y]=AW\"s4tUh{ XGcl\":.}+ "
    "gOWflMK&{!*'>UuV>C{xwr|)@qN0sBy`{)9e:A'%e&rK/a3AqW$psVFTx0lGDXMI "
    "?5Vb2>&(4BqA_{R)T}~B0]%2ghoKG'k.?E)3WmT^LxT[8=kP79t@XM!Cbp`ZhssuEG)iNRv&#"
    "U7sS4/ xMkp\" "
    "e+x|B?C\"f-N2S?\"[o&e~Zti(+u@3ck%,uQUqDJJoS.1Y$fbR<m>#ze{<5||~iegh=N@Q;"
    "dIF\\)Fh?iG,*}:uH$DHKgt/"
    "zy35=Eoc4nv8jbaM0MyF\u007F}vXDFvnnEhEu393zih\"{TO}->iEL^~aCI]dEF/"
    "KOxu\\~^v\"V_A%b@6\u007F(zXvCEw!67&Ev8:kbL}r}1Q=$|=fx45X}*/)|/"
    "Wy^4etaY4R>\"+V7wP]O~SuD>!8Hi7/\\S>rQQi\"vQ{32=.`[<3P "
    "k]POXX?'z!`\"Rd3\\O[+`W{pBrCT(fK6IGF;yn])xP[m]Q'0{8q| "
    "!8rIR\u007F!%thk%R?ITLS/*Lx+r<4kOhFs%3&@W*XVf!` "
    "YZy\"PRB61r'R5s\u007FM;LuWXn.AXFHDd3RGXl7xfM{RZ-7{(rz15\\\\6#%n0t "
    "xEi#Gu'lJ!1&\"4m6(x{iQN\u007FRs$jtODl9;z#\"b0v-TzhG,(hdd?oP$ix<[Ho/"
    "?FM~HlcFA!pwXjB?W,n&\"\"}'!5yov`#7/$)g$h)!(0AS7  "
    "5:^gZ\u007Frkr?Sg86+7o;G(&;NPAU*Du(-QQi.gW}TsQ "
    "c+Z\\bZz6&;^WEAzYy;6pDOjpN6~A~J;X3k|mW]xH8b9y)\u007F^j>h|z1/"
    "3^9G$jK2Q=-Wgxor{q|xZ=JxW1^j*4#=B!)wV??`Z~h>Kg,v^h|stV\u007FD*%avAupk>"
    "T59bH_e-*\u007Fw%b5wZ.9CGGPuwFAm.uDa5xGH^`{u-lKF&*CW/(&:CqiQSH[D.$wsi:h$/"
    "IJP/Ocp8nx^)J>8y}+j7 "
    "3Q@\\r(QD4r1+tP<D.behc03)N>nAYAM\"bTHyvuV#CZqU'2Ut>G*A*]C(zf9]-<u\"wrl`"
    "IAkfH;oi^!T'~p5W~3?Jce>((o'<a!>foJDKn&`wVTh2YO=eH$Y;\"g^+4 "
    "Q\u007FZ,Vdy*jIe-`AA\\c[=7t7Is1{\":E$c-f\\A}0,Oa~2rxoMP|vE$H3v\\kq "
    "Y$f_igYkW51cY}";

std::string one_time_pad(std::string msg, int enc_dec);

std::string encrypt(std::string msg, Method method);
std::string decrypt(std::string msg, Method method);
} // namespace Encryption
